package com.thirtydegreesray.openhub.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table "IGNORED_REPO".
*/
public class IgnoredRepoDao extends AbstractDao<IgnoredRepo, String> {

    public static final String TABLENAME = "IGNORED_REPO";

    /**
     * Properties of entity IgnoredRepo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FullName = new Property(0, String.class, "fullName", true, "FULL_NAME");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
        public final static Property Language = new Property(3, String.class, "language", false, "LANGUAGE");
        public final static Property StargazersCount = new Property(4, Integer.class, "stargazersCount", false, "STARGAZERS_COUNT");
        public final static Property ForksCount = new Property(5, Integer.class, "forksCount", false, "FORKS_COUNT");
        public final static Property OwnerLogin = new Property(6, String.class, "ownerLogin", false, "OWNER_LOGIN");
        public final static Property OwnerAvatarUrl = new Property(7, String.class, "ownerAvatarUrl", false, "OWNER_AVATAR_URL");
        public final static Property IgnoredAt = new Property(8, java.util.Date.class, "ignoredAt", false, "IGNORED_AT");
    }


    public IgnoredRepoDao(DaoConfig config) {
        super(config);
    }

    public IgnoredRepoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IGNORED_REPO\" (" + //
                "\"FULL_NAME\" TEXT PRIMARY KEY NOT NULL ," + // 0: fullName
                "\"NAME\" TEXT," + // 1: name
                "\"DESCRIPTION\" TEXT," + // 2: description
                "\"LANGUAGE\" TEXT," + // 3: language
                "\"STARGAZERS_COUNT\" INTEGER," + // 4: stargazersCount
                "\"FORKS_COUNT\" INTEGER," + // 5: forksCount
                "\"OWNER_LOGIN\" TEXT," + // 6: ownerLogin
                "\"OWNER_AVATAR_URL\" TEXT," + // 7: ownerAvatarUrl
                "\"IGNORED_AT\" INTEGER);"); // 8: ignoredAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IGNORED_REPO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IgnoredRepo entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getFullName());

        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }

        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }

        String language = entity.getLanguage();
        if (language != null) {
            stmt.bindString(4, language);
        }

        Integer stargazersCount = entity.getStargazersCount();
        if (stargazersCount != null) {
            stmt.bindLong(5, stargazersCount);
        }

        Integer forksCount = entity.getForksCount();
        if (forksCount != null) {
            stmt.bindLong(6, forksCount);
        }

        String ownerLogin = entity.getOwnerLogin();
        if (ownerLogin != null) {
            stmt.bindString(7, ownerLogin);
        }

        String ownerAvatarUrl = entity.getOwnerAvatarUrl();
        if (ownerAvatarUrl != null) {
            stmt.bindString(8, ownerAvatarUrl);
        }

        java.util.Date ignoredAt = entity.getIgnoredAt();
        if (ignoredAt != null) {
            stmt.bindLong(9, ignoredAt.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IgnoredRepo entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getFullName());

        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }

        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }

        String language = entity.getLanguage();
        if (language != null) {
            stmt.bindString(4, language);
        }

        Integer stargazersCount = entity.getStargazersCount();
        if (stargazersCount != null) {
            stmt.bindLong(5, stargazersCount);
        }

        Integer forksCount = entity.getForksCount();
        if (forksCount != null) {
            stmt.bindLong(6, forksCount);
        }

        String ownerLogin = entity.getOwnerLogin();
        if (ownerLogin != null) {
            stmt.bindString(7, ownerLogin);
        }

        String ownerAvatarUrl = entity.getOwnerAvatarUrl();
        if (ownerAvatarUrl != null) {
            stmt.bindString(8, ownerAvatarUrl);
        }

        java.util.Date ignoredAt = entity.getIgnoredAt();
        if (ignoredAt != null) {
            stmt.bindLong(9, ignoredAt.getTime());
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }

    @Override
    public IgnoredRepo readEntity(Cursor cursor, int offset) {
        IgnoredRepo entity = new IgnoredRepo( //
            cursor.getString(offset + 0), // fullName
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // description
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // language
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // stargazersCount
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // forksCount
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ownerLogin
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // ownerAvatarUrl
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)) // ignoredAt
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, IgnoredRepo entity, int offset) {
        entity.setFullName(cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLanguage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStargazersCount(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setForksCount(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setOwnerLogin(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setOwnerAvatarUrl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIgnoredAt(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
     }

    @Override
    protected final String updateKeyAfterInsert(IgnoredRepo entity, long rowId) {
        return entity.getFullName();
    }

    @Override
    public String getKey(IgnoredRepo entity) {
        if(entity != null) {
            return entity.getFullName();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(IgnoredRepo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
