package com.thirtydegreesray.openhub.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "IGNORED_REPO".
 *
 * Keyed by fullName ("owner/repo"), not a numeric repo id: Trending's
 * scraped Repository objects never get Repository.setId() called
 * (RepositoriesPresenter.parseTrendingRepositoryData() has no numeric id to
 * scrape from GitHub's HTML), so every Trending repo's id defaults to 0 -
 * using that as a primary key would conflate every ignored Trending repo
 * into a single row. fullName is reliably present from both Trending (HTML)
 * and Created (search API).
 *
 * Self-contained (denormalized display fields, no LocalRepo join) for the
 * same reason: LocalRepo is also keyed by numeric id, which Trending repos
 * don't have.
 */
@Entity
public class IgnoredRepo {

    @Id
    @NotNull
    private String fullName;

    private String name;
    private String description;
    private String language;
    private Integer stargazersCount;
    private Integer forksCount;
    private String ownerLogin;
    private String ownerAvatarUrl;
    private java.util.Date ignoredAt;

    @Generated
    public IgnoredRepo() {
    }

    public IgnoredRepo(String fullName) {
        this.fullName = fullName;
    }

    @Generated
    public IgnoredRepo(String fullName, String name, String description, String language, Integer stargazersCount, Integer forksCount, String ownerLogin, String ownerAvatarUrl, java.util.Date ignoredAt) {
        this.fullName = fullName;
        this.name = name;
        this.description = description;
        this.language = language;
        this.stargazersCount = stargazersCount;
        this.forksCount = forksCount;
        this.ownerLogin = ownerLogin;
        this.ownerAvatarUrl = ownerAvatarUrl;
        this.ignoredAt = ignoredAt;
    }

    @NotNull
    public String getFullName() {
        return fullName;
    }

    public void setFullName(@NotNull String fullName) {
        this.fullName = fullName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public Integer getStargazersCount() {
        return stargazersCount;
    }

    public void setStargazersCount(Integer stargazersCount) {
        this.stargazersCount = stargazersCount;
    }

    public Integer getForksCount() {
        return forksCount;
    }

    public void setForksCount(Integer forksCount) {
        this.forksCount = forksCount;
    }

    public String getOwnerLogin() {
        return ownerLogin;
    }

    public void setOwnerLogin(String ownerLogin) {
        this.ownerLogin = ownerLogin;
    }

    public String getOwnerAvatarUrl() {
        return ownerAvatarUrl;
    }

    public void setOwnerAvatarUrl(String ownerAvatarUrl) {
        this.ownerAvatarUrl = ownerAvatarUrl;
    }

    public java.util.Date getIgnoredAt() {
        return ignoredAt;
    }

    public void setIgnoredAt(java.util.Date ignoredAt) {
        this.ignoredAt = ignoredAt;
    }

}
