package com.thirtydegreesray.openhub.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MY_TOPIC".
 */
@Entity
public class MyTopic {

    @Id
    @NotNull
    private String slug;

    private int order;
    private boolean selected;

    @Generated
    public MyTopic() {
    }

    public MyTopic(String slug) {
        this.slug = slug;
    }

    @Generated
    public MyTopic(String slug, int order, boolean selected) {
        this.slug = slug;
        this.order = order;
        this.selected = selected;
    }

    @NotNull
    public String getSlug() {
        return slug;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSlug(@NotNull String slug) {
        this.slug = slug;
    }

    public int getOrder() {
        return order;
    }

    public void setOrder(int order) {
        this.order = order;
    }

    public boolean getSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

}
