package com.thirtydegreesray.openhub.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table "MY_TOPIC".
*/
public class MyTopicDao extends AbstractDao<MyTopic, String> {

    public static final String TABLENAME = "MY_TOPIC";

    /**
     * Properties of entity MyTopic.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Slug = new Property(0, String.class, "slug", true, "SLUG");
        public final static Property Order = new Property(1, int.class, "order", false, "ORDER");
        public final static Property Selected = new Property(2, boolean.class, "selected", false, "SELECTED");
    }


    public MyTopicDao(DaoConfig config) {
        super(config);
    }

    public MyTopicDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_TOPIC\" (" + //
                "\"SLUG\" TEXT PRIMARY KEY NOT NULL ," + // 0: slug
                "\"ORDER\" INTEGER NOT NULL ," + // 1: order
                "\"SELECTED\" INTEGER NOT NULL );"); // 2: selected
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_TOPIC\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MyTopic entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getSlug());
        stmt.bindLong(2, entity.getOrder());
        stmt.bindLong(3, entity.getSelected() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MyTopic entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getSlug());
        stmt.bindLong(2, entity.getOrder());
        stmt.bindLong(3, entity.getSelected() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }

    @Override
    public MyTopic readEntity(Cursor cursor, int offset) {
        MyTopic entity = new MyTopic( //
            cursor.getString(offset + 0), // slug
            cursor.getInt(offset + 1), // order
            cursor.getShort(offset + 2) != 0 // selected
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, MyTopic entity, int offset) {
        entity.setSlug(cursor.getString(offset + 0));
        entity.setOrder(cursor.getInt(offset + 1));
        entity.setSelected(cursor.getShort(offset + 2) != 0);
     }

    @Override
    protected final String updateKeyAfterInsert(MyTopic entity, long rowId) {
        return entity.getSlug();
    }

    @Override
    public String getKey(MyTopic entity) {
        if(entity != null) {
            return entity.getSlug();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MyTopic entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
